### ISSUE TITLE
upgrade to Node 12

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/deploy-bits#3]
```
$ node -v
v12.14.1
$ node -e 'require("@cypress/deploy-bits")'
fs.js:27
const { Math, Object } = primordials;
                         ^

ReferenceError: primordials is not defined
    at fs.js:27:26
    at req_ (/Users/gleb/git/cypress-documentation/node_modules/natives/index.js:143:24)
    at Object.req [as require] (/Users/gleb/git/cypress-documentation/node_modules/natives/index.js:55:10)
    at Object.<anonymous> (/Users/gleb/git/cypress-documentation/node_modules/vinyl-fs/node_modules/graceful-fs/fs.js:1:37)
```

**Comment by bahmutov** [comment]
The `gulp` v3 is the problem

```
$ node -e 'require("gulp")'
fs.js:27
const { Math, Object } = primordials;
                         ^

ReferenceError: primordials is not defined
    at fs.js:27:26
    at req_ (/Users/gleb/git/deploy-bits/node_modules/natives/index.js:143:24)
    at Object.req [as require] (/Users/gleb/git/deploy-bits/node_modules/natives/index.js:55:10)
    at Object.<anonymous> (/Users/gleb/git/deploy-bits/node_modules/graceful-fs/fs.js:1:37)
    at Module._compile (internal/modules/cjs/loader.js:955:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
    at Module.require (internal/modules/cjs/loader.js:848:19)
    at require (internal/modules/cjs/helpers.js:74:18)
```

**Comment by bahmutov** [comment]
`gulp` is used from s3-publish.js

**Comment by bahmutov** [comment]
ughh, need to switch from Travis to GH Actions to publish new version

**Comment by bahmutov** [comment]
Upgraded dependency `gulp` and `gulp-awspublish` and witched to using GitHub Actions to publish
